library(randomForest)

# Loading Top DEGs with F statistics > 20 (1846 genes)
degs <- read.csv("results/degs_original_f20.csv")

# Loading cluster information from original_study_analysis.R
metadata <- read.csv("results/metadata_clusters.csv", row.names = 1)
metadata$clusters <- factor(metadata$clusters)

# Loading data generated by batch_correct_microarray.R
training_data <- readRDS("data/processed/microarray/batch/original_study/var_collapsed.rds")

top_degs <- training_data[degs$X,]

# Random Forest
model <- randomForest(
  t(top_degs),
  metadata$clusters,
  ntree = 2000,
  mtry = 40,
  nodesize = 1
)

saveRDS(model, file = "models/trained/random_forest.rds")

# Importance matrix
importance_scores <- importance(model)

# Top 10 genes
head(importance_scores[order(-importance_scores[, 1]), ], 10)

# Plot
varImpPlot(model, main = "Random Forest Feature Importance")

##### Using the 1500 var genes
# Loading top var genes
top_var_genes <- read.csv("results/top_1500_var_genes.csv")$x

top_var <- training_data[top_var_genes,]

model_var <- randomForest(
  t(top_var),
  metadata$clusters,
  ntree = 2000,
  mtry = 40,
  nodesize = 1
)

saveRDS(model_var, file = "models/trained/top1500_var/random_forest.rds")

# Importance matrix
importance_scores_var <- importance(model_var)

# Top 10 genes
head(importance_scores_var[order(-importance_scores_var[, 1]), ], 10)

# Plot
varImpPlot(model_var, main = "Random Forest Feature Importance")