library(xgboost)

# Loading Top DEGs with F statistics > 20 (1846 genes)
degs <- read.csv("results/degs_original_f20.csv")

# Loading cluster information from original_study_analysis.R
metadata <- read.csv("results/metadata_clusters.csv", row.names = 1)
metadata$clusters <- factor(metadata$clusters)

# Loading data generated by batch_correct_microarray.R
training_data <- readRDS("data/processed/microarray/batch/original_study/var_collapsed.rds")

top_df <- training_data[degs$X,]

# XGBoost
labels <- as.numeric(metadata$clusters) - 1

xgb_train <- xgb.DMatrix(data = t(top_df), label = labels)

params <- list(
  max_depth = 4,
  eta = 0.01,
  objective = "multi:softprob",
  num_class = length(levels(metadata$clusters)),  # 3 clusters
  eval_metric = "mlogloss",
  subsample = 0.7,
  colsample_bytree = 0.6,
  lambda = 5
)

model_xgb <- xgb.train(
  data = xgb_train,
  params = params,
  nrounds = 5000,
  early_stopping_rounds = 50,
  evals = list(train = xgb_train),
  verbose = 1
)
saveRDS(model_xgb, file = "models/trained/xgboost.rds")

feature_names <- rownames(top_df)

importance_matrix <- xgb.importance(feature_names = feature_names, model = model_xgb)

print(importance_matrix[1:10])

xgb.plot.importance(importance_matrix = importance_matrix, top_n = 10)

##### Using the 1500 var genes
# Loading top var genes
top_var_genes <- read.csv("results/top_1500_var_genes.csv")$x

top_var <- training_data[top_var_genes,]

xgb_train_var <- xgb.DMatrix(data = t(top_var), label = labels)

model_xgb_var <- xgb.train(
  data = xgb_train_var,
  params = params,
  nrounds = 5000,
  early_stopping_rounds = 50,
  evals = list(train = xgb_train_var),
  verbose = 0
)
saveRDS(model_xgb_var, file = "models/trained/top1500_var/xgboost.rds")

feature_names_var <- rownames(top_var)

importance_matrix_var <- xgb.importance(feature_names = feature_names_var, model = model_xgb_var)

print(importance_matrix_var[1:10])

xgb.plot.importance(importance_matrix = importance_matrix_var, top_n = 10)