library(glmnet)

# Loading cluster information from original_study_analysis.R
metadata <- read.csv("results/metadata_clusters.csv", row.names = 1)
metadata$clusters <- factor(metadata$clusters)

# Loading Top DEGs with F statistics > 20 (1846 genes)
degs <- read.csv("results/degs_original_f20.csv")

# Loading data generated by batch_correct_microarray.R
training_data <- readRDS("data/processed/microarray/batch/original_study/var_collapsed.rds")

top_df <- training_data[degs$X,]

# Penalized Logistic Regression - glmnet
y_train <- metadata$clusters
x_train <- t(top_df)

cv_fit <- cv.glmnet(
  x = x_train,
  y = y_train,
  family = "multinomial",
  alpha = 1,  # Lasso for feature selection
  nfolds = 5  # Use 5-fold CV due to small sample size
)
saveRDS(cv_fit, file = "models/trained/glmnet.rds")

##### Using the 1500 var genes
# Loading top var genes
top_var_genes <- read.csv("results/top_1500_var_genes.csv")$x

top_var <- training_data[top_var_genes,]

x_train_var <- t(top_var)

cv_fit_var <- cv.glmnet(
  x = x_train_var,
  y = y_train,
  family = "multinomial",
  alpha = 1,  # Lasso for feature selection
  nfolds = 5  # Use 5-fold CV due to small sample size
)
saveRDS(cv_fit_var, file = "models/trained/top1500_var/glmnet.rds")