library(pls)

# Loading cluster information from original_study_analysis.R
metadata <- read.csv("results/metadata_clusters.csv", row.names = 1)
metadata$clusters <- factor(metadata$clusters)

# Loading Top DEGs with F statistics > 20 (1846 genes)
degs <- read.csv("results/degs_original_f20.csv")

# Loading data generated by batch_correct_microarray.R
training_data <- readRDS("data/processed/microarray/batch/original_study/var_collapsed.rds")

top_degs <- training_data[degs$X,]

# PLS-DA (Partial Least-Squares Discriminant Analysis)
y_train <- metadata$clusters

y_train_dummy <- model.matrix(~ y_train - 1)

x_train <- t(top_degs)

pls_model <- plsr(y_train_dummy ~ x_train, ncomp = 3)

saveRDS(pls_model, file = "models/trained/plsda.rds")

##### Using the 1500 var genes
# Loading top var genes
top_var_genes <- read.csv("results/top_1500_var_genes.csv")$x

top_var <- training_data[top_var_genes,]

x_train_var <- t(top_var)

pls_model_var <- plsr(y_train_dummy ~ x_train_var, ncomp = 3)

saveRDS(pls_model_var, file = "models/trained/top1500_var/plsda.rds")