library(tidyverse)
library(limma)

source("scripts/utils.R")

# Save RDS function
named_list_save_rds <- function(named_list, path) {
  for (name in names(named_list)) {
    file_path <- paste0(path, name, ".rds")

    object <- named_list[[name]]

    saveRDS(object, file_path)
  }
}

# Loading data generated by get_microarray_dataset.R
pascal <- read_csv("data/processed/microarray/mas5/pascal.csv")
birks <- read_csv("data/processed/microarray/mas5/birks.csv")
wang <- read_csv("data/processed/microarray/mas5/wang.csv")
amani <- read_csv("data/processed/microarray/mas5/amani.csv")


# Log2 and matrix, also removes gene and alt gene columns
expr_pascal <- log2_and_matrix(pascal)
expr_birks <- log2_and_matrix(birks)
expr_wang <- log2_and_matrix(wang)
expr_amani <- log2_and_matrix(amani)

## Original study
pascal_birks <- cbind(expr_pascal, expr_birks)

batch_pb <- c(
  rep("pascal", ncol(expr_pascal)),
  rep("birks", ncol(expr_birks))
)

## Collapsing genes then correcting for batch effect
pb_corrected <- limma::removeBatchEffect(pascal_birks, batch = batch_pb)

pb_corrected_gene <- remove_empty_probes(pb_corrected, pascal)

pb_corrected_var <- colapse_probes_gene(pb_corrected, gpl = "GPL570", method = "variance")
pb_corrected_mean <- colapse_probes_gene(pb_corrected, gpl = "GPL570", method = "mean")
pb_corrected_max <- colapse_probes_gene(pb_corrected, gpl = "GPL570", method = "max")

saveRDS(pb_corrected_var, "data/processed/microarray/batch/original_study/var_collapsed.rds")
saveRDS(pb_corrected_mean, "data/processed/microarray/batch/original_study/mean_collapsed.rds")
saveRDS(pb_corrected_max, "data/processed/microarray/batch/original_study/max_collapsed.rds")

# Test data
merged_data <- cbind(pb_corrected, expr_wang, expr_amani)

batch_test <- c(
  rep("original", ncol(pb_corrected)),
  rep("want", ncol(expr_wang)),
  rep("amani", ncol(expr_amani))
)

merged_data_corr <- limma::removeBatchEffect(merged_data, batch = batch_test)

clean_merged <- remove_empty_probes(merged_data_corr, wang)

test_data <- clean_merged[, (ncol(pb_corrected) + 1):length(batch_test)]

test_corrected_var <- colapse_probes_gene(test_data, gpl = "GPL570", method = "variance")
test_corrected_mean <- colapse_probes_gene(test_data, gpl = "GPL570", method = "mean")
test_corrected_max <- colapse_probes_gene(test_data, gpl = "GPL570", method = "max")

saveRDS(test_corrected_var, "data/processed/microarray/batch/original_study/test_var_collapsed.rds")
saveRDS(test_corrected_mean, "data/processed/microarray/batch/original_study/test_mean_collapsed.rds")
saveRDS(test_corrected_max, "data/processed/microarray/batch/original_study/test_max_collapsed.rds")