library(tidyverse)
library(limma)

source("scripts/utils.R")

# Save RDS function
named_list_save_rds <- function(named_list, path) {
  for (name in names(named_list)) {
    file_path <- paste0(path, name, ".rds")

    object <- named_list[[name]]

    saveRDS(object, file_path)
  }
}

# Loading data generated by get_microarray_dataset.R
pascal <- read_csv("data/processed/microarray/mas5/pascal.csv")
birks <- read_csv("data/processed/microarray/mas5/birks.csv")
wang <- read_csv("data/processed/microarray/mas5/wang.csv")
amani <- read_csv("data/processed/microarray/mas5/amani.csv")


# Log2 and matrix, also removes gene and alt gene columns
expr_pascal <- log2_and_matrix(pascal)
expr_birks <- log2_and_matrix(birks)
expr_wang <- log2_and_matrix(wang)
expr_amani <- log2_and_matrix(amani)

# All datasets
combined_expr <- cbind(expr_pascal, expr_birks, expr_wang, expr_amani)

batch <- c(
  rep("pascal", ncol(expr_pascal)),
  rep("birks", ncol(expr_birks)),
  rep("wang", ncol(expr_wang)),
  rep("amani", ncol(expr_amani))
)

# Removing probes that don't map to genes
# remove_empty_probes requires a table with "Gene" column
# We use pascal but all of our microarrays contain the same Gene column
combined_gene <- remove_empty_probes(combined_expr, pascal)

combined_corrected <- limma::removeBatchEffect(combined_gene, batch = batch)

# data max "iloc"
pascal_iloc <- ncol(expr_pascal)
birks_iloc <- pascal_iloc + ncol(expr_birks)
wang_iloc <- birks_iloc + ncol(expr_wang)
amani_iloc <- wang_iloc + ncol(expr_amani)

# Batch corrected datasets
pascal_corrected <- combined_corrected[, 1:pascal_iloc]
birks_corrected <- combined_corrected[, (pascal_iloc + 1):birks_iloc]
wang_corrected <- combined_corrected[, (birks_iloc + 1):wang_iloc]
amani_corrected <- combined_corrected[, (wang_iloc + 1):amani_iloc]

# Saving batch corrected datasets
batch_corr <- list(
  pascal_corrected = pascal_corrected,
  birks_corrected = birks_corrected,
  wang_corrected = wang_corrected,
  amani_corrected = amani_corrected
)

path_batch_corr <- "data/processed/microarray/batch/"

named_list_save_rds(batch_corr, path = path_batch_corr)

# Collapsing multiple probes linked to the same gene
# to the one with highest variance (utils.R)
collapsed_pascal <- colapse_probes_gene(pascal_corrected, gpl = "GPL570")
collapsed_birks <- colapse_probes_gene(birks_corrected, gpl = "GPL570")
collapsed_wang <- colapse_probes_gene(wang_corrected, gpl = "GPL570")
collapsed_amani <- colapse_probes_gene(amani_corrected, gpl = "GPL570")

# Saving batch_collapsed RDS
batch_collapsed <- list(
  batch_collapsed_pascal = collapsed_pascal,
  batch_collapsed_birks = collapsed_birks,
  batch_collapsed_wang = collapsed_wang,
  batch_collapsed_amani = collapsed_amani
)
path_batch_collapsed <- "data/processed/microarray/batch/collapsed/"

named_list_save_rds(batch_collapsed, path = path_batch_collapsed)

# Globally Scaled batch corrected datasets
combined_scaled <- t(scale(t(combined_corrected)))

pascal_scaled <- combined_scaled[, 1:pascal_iloc]
birks_scaled <- combined_scaled[, (pascal_iloc + 1):birks_iloc]
wang_scaled <- combined_scaled[, (birks_iloc + 1):wang_iloc]
amani_scaled <- combined_scaled[, (wang_iloc + 1):amani_iloc]

# Saving scaled batch corrected
scaled_batch_corr <- list(
  pascal_scaled = pascal_scaled,
  birks_scaled = birks_scaled,
  wang_scaled = wang_scaled,
  amani_scaled = amani_scaled
)
path_scaled_batch_corr <- "data/processed/microarray/batch/scaled/"

named_list_save_rds(scaled_batch_corr, path = path_scaled_batch_corr)

# Globally Scaled and collapsed
scaled_collapsed_pascal <- colapse_probes_gene(pascal_scaled, gpl = "GPL570")
scaled_collapsed_birks <- colapse_probes_gene(birks_scaled, gpl = "GPL570")
scaled_collapsed_wang <- colapse_probes_gene(wang_scaled, gpl = "GPL570")
scaled_collapsed_amani <- colapse_probes_gene(amani_scaled, gpl = "GPL570")

# Saving scaled and collapsed
scaled_batch_collapsed <- list(
  scaled_collapsed_pascal = scaled_collapsed_pascal,
  scaled_collapsed_birks = scaled_collapsed_birks,
  scaled_collapsed_wang = scaled_collapsed_wang,
  scaled_collapsed_amani = scaled_collapsed_amani
)

path_scaled_batch_collapsed <- "data/processed/microarray/batch/scaled/collapsed/"

named_list_save_rds(scaled_batch_collapsed, path = path_scaled_batch_collapsed)