library(tidyverse)
library(limma)
library(matrixStats)

# Loading data generated by get_microarray_metadata.R
metadata <- read_csv("data/microarray/microarray_metadata.csv")

# Loading data generated by get_microarray_dataset.R
microarray <- read_csv("data/microarray/microarray_dataset.csv")


samples_to_group <- metadata %>%
  select(gsm, subgrouping_based_on_450k_methylation_data, sample_name) %>%
  drop_na() %>%
  rename(group = subgrouping_based_on_450k_methylation_data) %>%
  arrange(gsm)

microarray_26_samples <- microarray %>%
  select(all_of(samples_to_group$gsm)) %>%
  as.data.frame()

rownames(microarray_26_samples) <- microarray$ID

# All colnames in order and matching
all(colnames(microarray_26_samples) == samples_to_group$gsm)

# Log conversion
microarray_26_samples_log2 <- log2(microarray_26_samples)


### Finding top 1500 DEGs with limma
group_factor <- factor(samples_to_group$group, levels = c("SHH", "TYR", "MYC"))

design <- model.matrix(~0 + group_factor)
colnames(design) <- gsub("group_factor", "", colnames(design))

fit <- lmFit(microarray_26_samples_log2, design)

contrast_matrix <- makeContrasts(
  TYR_vs_SHH = TYR - SHH,
  MYC_vs_SHH = MYC - SHH,
  TYR_vs_MYC = TYR - MYC,
  levels = design
)

fit2 <- contrasts.fit(fit, contrast_matrix)

fit2 <- eBayes(fit2)

top_n <- 1500

top_1500_overall_degs <- topTable(
  fit2,
  number = top_n,
  adjust.method = "BH",
  sort.by = "F"
)

top_degs_df <- microarray %>%
  filter(ID %in% rownames(top_1500_overall_degs))

top_degs <- top_degs_df[, 4:70]
###

### Alternative approach, finding the top 1500 most variable genes
# in the 26 known samples
gene_vars_26 <- apply(microarray_26_samples_log2, 1, var)

top_var_genes_26 <- names(sort(gene_vars_26, decreasing = TRUE)[1:1500])

top_var_26 <- microarray %>%
  filter(ID %in% top_var_genes_26)
###

### Alternative approach 2, top 1500 most variable genes in all samples
only_data <- microarray[, 4:70]
rownames(only_data) = microarray$ID
gene_vars <- apply(only_data, 1, var)

top_var_genes <- names(sort(gene_vars, decreasing = TRUE)[1:1500])

top_var <- microarray %>%
  filter(ID %in% top_var_genes)
###

clust_methods <- c("ward.D",
  "ward.D2",
  "single",
  "complete",
  "average",
  "mcquitty",
  "median",
  "centroid"
)

# Clustering DEGs from limma
sample_dist <- as.dist(1 - cor(top_degs, method = "pearson"))
hc_limma <- list()
cluster_limma <-  list()
for (method in clust_methods){
  hc_limma[[method]] <- hclust(sample_dist, method = method)
  cluster_limma[[method]] <- cutree(hc_limma[[method]], k = 3)
}

comparison <- as.data.frame(cluster_limma)
comparison$samples <- rownames(comparison)

comparison$original_subgroup <- metadata$subrouping_based_on_affymetrix_gene_expression_data[
  match(comparison$samples, metadata$gsm)
]

metadata$my_clusterd2 <- as.factor(my_clustersd2)
####
distance_matrix <- dist(t(top_degs))

hc <- hclust(distance_matrix, method = "ward.D2")
plot(hc)
rect.hclust(hc, k = 3, border = "red")


my_clusters <- cutree(hc, k = 3)

metadata$my_cluster <- as.factor(my_clusters)
sample_order <- metadata$gsm

comparison <- data.frame(
  sample = sample_order,
  my_cluster = my_clusters,
  stringsAsFactors = FALSE
)

comparison$original_subgroup <- metadata$subrouping_based_on_affymetrix_gene_expression_data[
  match(comparison$sample, metadata$sample_name)
]

# Checking how many samples matched
sum(!is.na(comparison$original_subgroup))

# PCA on all genes
only_counts <- microarray[, -c(1:3)]

pca <- prcomp(t(only_counts), scale = TRUE)

plot(pca$x[, 1], pca$x[, 2])

pca_var <- pca$sdev^2

pca_var_percent <- round(pca_var/sum(pca_var)*100, 1)

barplot(pca_var_percent,
  main = "Scree plot",
  xlab = "Principal component",
  ylab = "Percent variation"
)

pca_data <- data.frame(gsm = rownames(pca$x),
  pc1 = pca$x[, 1],
  pc2 = pca$x[, 2]
  ) %>%
  inner_join(., metadata, by = "gsm")

ggplot(data = pca_data, aes(x = pc1, y = pc2, color = project))+
  geom_point()+
  xlab(paste("PC1 - ", pca_var_percent[1], "%"))+
  ylab(paste("PC2 - ", pca_var_percent[2], "%"))+
  ggtitle("PCA")

# We might need to correct for batch effect

