library(tidyverse)
library(limma)
library(matrixStats)

# Loading data generated by get_microarray_metadata.R
metadata <- read_csv("data/microarray/microarray_metadata.csv")

# Loading data generated by get_microarray_dataset.R
microarray <- read_csv("data/microarray/microarray_dataset.csv")

# Collapsing multiple probes linked to the same gene
# to the one with highest variance
microarray[,4:70] <- log2(microarray[,4:70] +1)
colapesed_microarray <- microarray %>%
  mutate(variance = rowVars(as.matrix(across(where(is.numeric))))) %>%
  drop_na(Gene) %>%
  group_by(Gene) %>%
  slice_max(order_by = variance, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  arrange(desc(variance)) %>%
  column_to_rownames("Gene") %>%
  select(- ID, - Gene_alt)

top_var_genes <- colapesed_microarray[1:1500,] %>%
  select(-variance)
top_var_scaled <- t(scale(t(top_var_genes)))


# Compute correlation distance
dist_matrix <- as.dist(1 - cor(top_var_scaled, method = "pearson"))

# Hierarchical clustering
hc <- hclust(dist_matrix, method = "average")

# Dendrogram plot
plot(as.dendrogram(hc, hang = 1, label = NULL), yaxt = "n")
rect.hclust(hc, k = 3, border = "red")

clusters <- cutree(hc, k = 3)

# Original cluster was 22/23/22
table(clusters)


# Let's check for batch effect birks/pascal
pca <- prcomp(t(top_var_scaled), scale = TRUE)



pca_var <- pca$sdev^2

pca_var_percent <- round(pca_var/sum(pca_var)*100, 1)

barplot(pca_var_percent,
  main = "Scree plot",
  xlab = "Principal component",
  ylab = "Percent variation"
)

pca_data <- data.frame(gsm = rownames(pca$x),
  pc1 = pca$x[, 1],
  pc2 = pca$x[, 2]
  ) %>%
  inner_join(., metadata, by = "gsm")

ggplot(data = pca_data, aes(x = pc1, y = pc2, color = project))+
  geom_point()+
  xlab(paste("PC1 - ", pca_var_percent[1], "%"))+
  ylab(paste("PC2 - ", pca_var_percent[2], "%"))+
  ggtitle("PCA")

# We might need to correct for batch effect...
colapesed_microarray_no_var <- colapesed_microarray %>%
  select(-variance)

# Ensuring the same order to create batch vector
metadata <- metadata %>%
  filter(gsm %in% colnames(colapesed_microarray_no_var)) %>%
  arrange(match(gsm, colnames(colapesed_microarray_no_var)))

all(metadata$gsm == colnames(colapesed_microarray_no_var))
batch <- metadata$project

# Using limma to remove batch effect
expr_corrected <- limma::removeBatchEffect(colapesed_microarray_no_var, batch = batch)

# Retrying PCA
pca_corrected <- prcomp(t(expr_corrected), scale = FALSE)

pca_data_corrected <- data.frame(
  gsm = rownames(pca_corrected$x),
  pc1 = pca_corrected$x[, 1],
  pc2 = pca_corrected$x[, 2]
) %>%
  inner_join(metadata, by = "gsm")

ggplot(pca_data_corrected, aes(x = pc1, y = pc2, color = project)) +
  geom_point(size = 3) +
  xlab("PC1") + ylab("PC2") +
  ggtitle("PCA after batch correction") +
  theme_bw()


# Since we corrected for batch effect using all genes
# We recalculated variance and selected top 1500
genes_variance <- apply(expr_corrected, 1, var, na.rm = TRUE)
top_genes_corrected <- names(sort(genes_variance, decreasing = TRUE)[1:1500])
top_corrected <- expr_corrected[top_genes_corrected, ]

# From the top 1500 variance genes 63 changed with the batch correction
sum(!rownames(top_var_genes) %in% rownames(top_corrected))

top_var_scaled_corrected <- t(scale(t(top_corrected)))
dist_matrix <- as.dist(1 - cor(top_var_scaled_corrected, method = "pearson"))

# Hierarchical clustering
hc <- hclust(dist_matrix, method = "average")

# Dendrogram plot
plot(as.dendrogram(hc, hang = 1, label = NULL), yaxt = "n")
rect.hclust(hc, k = 3, border = "red")

clusters <- cutree(hc, k = 3)

# One sample seems to be different then the original study
table(clusters)

metadata$clusters <- as.factor(clusters)

# Let's identify the clusters based on the key genes in the article

gene_expression_df <- data.frame(
  gsm = colnames(expr_corrected),
  tyr = expr_corrected["TYR",],
  mycn = expr_corrected["MYCN",],
  myc = expr_corrected["MYC",],
  mitf = expr_corrected["MITF",],
  gli2 = expr_corrected["GLI2",],
  hotair = expr_corrected["HOTAIR",]
) %>%
  left_join(., metadata %>% select(gsm, clusters), by = "gsm")

# Create the boxplot
for (gene in colnames(gene_expression_df)[2:7]){
  p <- ggplot(gene_expression_df, aes(x = clusters, y = .data[[gene]], fill = clusters)) +
  geom_boxplot() +
  labs(title = "Boxplot of Values by Group",
       y = "Observed Value",
       x = gene) +
  theme_minimal()

  print(p)
}

metadata <- metadata %>%
  mutate(clusters = case_when(
    clusters == 1 ~ "SHH",
    clusters == 2 ~ "TYR",
    clusters ==  3 ~ "MYC"
  ))

# Now that we have the subgroups identified we can use limma to find DEGs

metadata

metadata$clusters <- factor(metadata$clusters)
metadata$project <- factor(metadata$project)

write.csv(metadata, file = "results/metadata_clusters.csv")

design <- model.matrix(~ 0 + clusters + project, data = metadata)

colnames(design) <- c(levels(metadata$clusters), levels(metadata$project)[-1])

fit <- lmFit(log2(colapesed_microarray) %>% select(-variance), design)

contrast_matrix <- makeContrasts(
  TYR_vs_SHH = TYR - SHH,
  MYC_vs_SHH = MYC - SHH,
  TYR_vs_MYC = TYR - MYC,
  levels = design
)

fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

top_all <- topTable(fit2, adjust.method="fdr", number=Inf)
top_all["TYR",]
