source("scripts/utils.R")

# Loading data generated by get_microarray_metadata.R
metadata <- read_csv("data/microarray/microarray_metadata.csv")

# Loading data generated by get_microarray_dataset.R
pascal <- read_csv("data/microarray/pascal.csv")
birks <- read_csv("data/microarray/birks.csv")

# Log2 and matrix
expr_pascal <- log2_and_matrix(pascal)
expr_birks <- log2_and_matrix(birks)

combined_expr <- cbind(expr_pascal, expr_birks)

# Collapsing multiple probes linked to the same gene
# to the one with highest variance
colapesed_microarray <- colapse_probes(combined_expr, pascal)

top_var_genes <- colapesed_microarray[1:1500,]
top_var_scaled <- t(scale(t(top_var_genes)))


# Compute correlation distance
dist_matrix <- as.dist(1 - cor(top_var_scaled, method = "pearson"))

# Hierarchical clustering
hc <- hclust(dist_matrix, method = "average")

# Dendrogram plot
plot(as.dendrogram(hc, hang = 1, label = NULL), yaxt = "n")
rect.hclust(hc, k = 3, border = "red")

clusters <- cutree(hc, k = 3)

# Original cluster was 22/23/22
table(clusters)


# Let's check for batch effect birks/pascal
pca <- prcomp(t(top_var_scaled), scale = TRUE)

pca_var <- pca$sdev^2

pca_var_percent <- round(pca_var/sum(pca_var)*100, 1)

barplot(pca_var_percent,
  main = "Scree plot",
  xlab = "Principal component",
  ylab = "Percent variation"
)

pca_data <- data.frame(gsm = rownames(pca$x),
  pc1 = pca$x[, 1],
  pc2 = pca$x[, 2]
  ) %>%
  inner_join(., metadata, by = "gsm")

ggplot(data = pca_data, aes(x = pc1, y = pc2, color = project))+
  geom_point()+
  xlab(paste("PC1 - ", pca_var_percent[1], "%"))+
  ylab(paste("PC2 - ", pca_var_percent[2], "%"))+
  ggtitle("PCA")

# We might need to correct for batch effect...
# Using data from batch_correct_microarray.R
original_corrected <- readRDS("data/processed/batch_collapsed/original.rds")

# Retrying PCA
pca_corrected <- prcomp(t(original_corrected), scale = FALSE)

pca_data_corrected <- data.frame(
  gsm = rownames(pca_corrected$x),
  pc1 = pca_corrected$x[, 1],
  pc2 = pca_corrected$x[, 2]
) %>%
  inner_join(metadata, by = "gsm")

ggplot(pca_data_corrected, aes(x = pc1, y = pc2, color = project)) +
  geom_point(size = 3) +
  xlab("PC1") + ylab("PC2") +
  ggtitle("PCA after batch correction") +
  theme_bw()


# Top 1500 most variable genes
top_genes_corrected <- original_corrected[1:1500,]

# From the top 1500 variance genes 189 changed with the batch correction
sum(!rownames(top_var_genes) %in% rownames(top_genes_corrected))

top_var_scaled_corrected <- t(scale(t(top_genes_corrected)))
dist_matrix <- as.dist(1 - cor(top_var_scaled_corrected, method = "pearson"))

# Hierarchical clustering
hc <- hclust(dist_matrix, method = "average")

# Dendrogram plot
plot(as.dendrogram(hc, hang = 1, label = NULL), yaxt = "n")
rect.hclust(hc, k = 3, border = "red")

clusters <- cutree(hc, k = 3)

# One sample seems to be different then the original study
table(clusters)

metadata$clusters <- as.factor(clusters)

# Let's identify the clusters based on the key genes in the article

target_genes <- c("TYR", "MITF", "MYCN", "GLI2", "MYC", "HOTAIR")

gene_expression_df <- t(original_corrected[target_genes, ]) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "gsm") %>%
  left_join(metadata %>% select(gsm, clusters), by = "gsm")

long_df <- gene_expression_df %>%
  pivot_longer(
    cols = all_of(target_genes),
    names_to = "gene",
    values_to = "expression"
  ) %>%
  mutate(gene = fct_relevel(gene, target_genes))

ggplot(long_df, aes(x = clusters, y = expression, fill = clusters)) +
  geom_boxplot() +
  facet_wrap(~gene, ncol = 2) +
  labs(
    title = "Key Gene Expression Levels by Cluster",
    y = "Expression Level",
    x = "Cluster"
  ) +
  theme_minimal() +
  theme(legend.position = "none")


metadata <- metadata %>%
  mutate(clusters = case_when(
    clusters == 1 ~ "SHH",
    clusters == 2 ~ "TYR",
    clusters ==  3 ~ "MYC"
  ))

# Now that we have the subgroups identified we can use limma to find DEGs
metadata

metadata$clusters <- factor(metadata$clusters)
metadata$project <- factor(metadata$project)

write.csv(metadata, file = "results/metadata_clusters.csv")

design <- model.matrix(~ 0 + clusters + project, data = metadata)

colnames(design) <- c(levels(metadata$clusters), levels(metadata$project)[-1])

fit <- lmFit(log2(colapesed_microarray) %>% select(-variance), design)

contrast_matrix <- makeContrasts(
  TYR_vs_SHH = TYR - SHH,
  MYC_vs_SHH = MYC - SHH,
  TYR_vs_MYC = TYR - MYC,
  levels = design
)

fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

top_all <- topTable(fit2, adjust.method="fdr", number=Inf)
top_all["TYR",]

metadata$con <- metadata$subrouping_based_on_affymetrix_gene_expression_data == metadata$clusters
