library(limma)
source("scripts/utils.R")

# Function create PCA
plot_pca <- function(top_scaled, metadata) {
  pca <- prcomp(t(top_scaled), scale = TRUE)

  pca_var <- pca$sdev^2

  pca_var_percent <- round(pca_var/sum(pca_var)*100, 1)

  pca_data <- data.frame(ind = rownames(pca$x),
    pc1 = pca$x[, 1],
    pc2 = pca$x[, 2]
  ) %>%
    inner_join(., metadata, by = "ind")

  ggplot(data = pca_data, aes(x = pc1, y = pc2, color = project))+
    geom_point()+
    xlab(paste("PC1 - ", pca_var_percent[1], "%"))+
    ylab(paste("PC2 - ", pca_var_percent[2], "%"))+
    ggtitle("PCA")

}

clustering <- function(top_scaled) {
  # Compute correlation distance
  dist_matrix <- as.dist(1 - cor(top_scaled, method = "pearson"))

  # Hierarchical clustering
  hc <- hclust(dist_matrix, method = "average")

  # Dendrogram plot
  plot(as.dendrogram(hc, hang = 1, label = NULL), yaxt = "n")
  rect.hclust(hc, k = 3, border = "red")

  clusters <- cutree(hc, k = 3)

  # Original cluster was 22/23/22
  table(clusters)

  clusters
}

# Loading data generated by get_microarray_metadata.R
metadata <- read.csv("data/raw/microarray/metadata/original_geo_metadata.csv", row.names = 1)

# Loading data generated by get_microarray_dataset.R
pascal <- read.csv("data/processed/microarray/mas5/pascal.csv")
birks <- read.csv("data/processed/microarray/mas5/birks.csv")

# Log2 and matrix, also drops gene and gene alt
expr_pascal <- log2_and_matrix(pascal)
expr_birks <- log2_and_matrix(birks)

combined_expr <- cbind(expr_pascal, expr_birks)

# Remove non mapping probes
clean_expr <- remove_empty_probes(combined_expr, pascal)

# Collapsing multiple probes linked to the same gene
# to the one with highest variance
colapesed_microarray <- colapse_probes_gene(clean_expr, gpl = "GPL570")

top_var_genes <- colapesed_microarray[1:1500,]

top_var_scaled <- t(scale(t(top_var_genes)))

# Hierarchical Clustering
clusters <- clustering(top_var_scaled)

# Original cluster was 22/23/22
table(clusters)

# Let's check for batch effect birks/pascal
plot_pca(top_var_scaled, metadata)

# We might need to correct for batch effect...
# Using data from batch_correct_microarray.R
original_corrected <- readRDS("data/processed/microarray/batch/original_study/var_collapsed.rds")

top_scaled_original <- t(scale(t(original_corrected[1:1500,])))
# Retrying PCA
plot_pca(top_scaled_original, metadata)

# From the top 1500 variance genes 189 changed with the batch correction
sum(!rownames(top_var_genes) %in% rownames(top_scaled_original))

top_1500_var_genes <- rownames(top_scaled_original)
write.csv(top_1500_var_genes, file = "results/top_1500_var_genes.csv")

top_var_scaled_corrected <- t(scale(t(top_scaled_original)))

# Hierarchical Clustering
clusters <- clustering(top_var_scaled_corrected)

# One sample seems to be different then the original study
table(clusters)

##### Testing other probe collapse methods
# Let's try to collapse probes to gene mean
original_mean <- readRDS("data/processed/microarray/batch/original_study/mean_collapsed.rds")

# Now we need to select the 1500 most variable genes
top_mean <- original_mean %>%
  mutate(variance = rowVars(as.matrix(across(where(is.numeric))))) %>%
  arrange(desc(variance)) %>%
  select(-variance) %>%
  slice_head(n = 1500)

scaled_top_mean <- t(scale(t(top_mean)))

clusters_mean <- clustering(scaled_top_mean)

# We've got the same classification
clusters_mean == clusters

# Repeating the same steps
# but now collapsing probe to the gene with the max mean expression
original_max <- readRDS("data/processed/microarray/batch/original_study/max_collapsed.rds")

top_max <- original_max %>%
  mutate(variance = rowVars(as.matrix(across(where(is.numeric))))) %>%
  arrange(desc(variance)) %>%
  select(-variance) %>%
  slice_head(n = 1500)

scaled_top_max<- t(scale(t(top_max)))

clusters_max <- clustering(scaled_top_max)

# We've got the same classification regardless of collapsing method
clusters_max == clusters

#####

metadata$clusters <- as.factor(clusters)

# Let's identify the clusters based on the key genes in the article

target_genes <- c("TYR", "MITF", "MYCN", "GLI2", "MYC", "HOTAIR")

gene_expression_df <- t(original_corrected[target_genes, ]) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "ind") %>%
  left_join(metadata %>% select(ind, clusters), by = "ind")

long_df <- gene_expression_df %>%
  pivot_longer(
    cols = all_of(target_genes),
    names_to = "gene",
    values_to = "expression"
  ) %>%
  mutate(gene = fct_relevel(gene, target_genes))

ggplot(long_df, aes(x = clusters, y = expression, fill = clusters)) +
  geom_boxplot() +
  facet_wrap(~gene, ncol = 2) +
  labs(
    title = "Key Gene Expression Levels by Cluster",
    y = "Expression Level",
    x = "Cluster"
  ) +
  theme_minimal() +
  theme(legend.position = "none")


metadata <- metadata %>%
  mutate(clusters = case_when(
    clusters == 1 ~ "SHH",
    clusters == 2 ~ "TYR",
    clusters ==  3 ~ "MYC"
  ))

metadata$clusters <- factor(metadata$clusters)
metadata$project <- factor(metadata$project)

write.csv(metadata, file = "results/metadata_clusters.csv")

# Now that we have the subgroups identified we can use limma to find DEGs
design <- model.matrix(~ 0 + clusters + project, data = metadata)

colnames(design) <- c(levels(metadata$clusters), levels(metadata$project)[-1])

fit <- lmFit(original_corrected, design)

contrast_matrix <- makeContrasts(
  TYR_vs_SHH = TYR - SHH,
  MYC_vs_SHH = MYC - SHH,
  TYR_vs_MYC = TYR - MYC,
  levels = design
)

fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

top_all <- topTable(fit2, adjust.method="fdr", number=Inf) %>%
  arrange(desc(F)) %>%
  filter(F > 20)

write.csv(top_all, file = "results/degs_original_f20.csv")
