metadata <- read.csv("results/metadata_clusters.csv", row.names = 1)
metadata$clusters <- factor(metadata$clusters)
# Loading data generated by get_microarray_dataset.R
microarray <- read_csv("data/microarray/microarray_dataset.csv")
microarray[,4:70] <- log2(microarray[,4:70] +1)