library(tidyverse)
library(limma)
library(matrixStats)
library(randomForest)
library(xgboost)

# Loading data generated by microarray.R
metadata <- read.csv("results/metadata_clusters.csv", row.names = 1)
metadata$clusters <- factor(metadata$clusters)
# Loading data generated by get_microarray_dataset.R
microarray <- read_csv("data/microarray/microarray_dataset.csv")
microarray[,4:70] <- log2(microarray[,4:70] +1)

wang <- read.csv("data/microarray/wang.csv")
wang[,4:12] <- log2(wang[,4:12] +1)

# Collapsing multiple probes linked to the same gene
# to the one with highest variance
collapsed_microarray <- microarray %>%
  mutate(variance = rowVars(as.matrix(across(where(is.numeric))))) %>%
  drop_na(Gene) %>%
  group_by(Gene) %>%
  slice_max(order_by = variance, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  arrange(desc(variance)) %>%
  column_to_rownames("Gene") %>% 
  dplyr::select(- ID, - Gene_alt, -variance) %>%
  limma::normalizeBetweenArrays(.)

# Loading data generated by get_rnsaeq_data.R
rnaseq <- read_csv("data/rnaseq/rnaseq.csv") 

colnames(rnaseq)[1] <- "gene"

# Genes with the same symbol get a single value by summing their counts
# Might be a strong bias source
# But only very few genes are affected by it
rnaseq <- rnaseq %>%
  drop_na(gene) %>%
  group_by(gene) %>%
  summarise(across(starts_with("SRR"), sum)) %>%
  column_to_rownames("gene")

log2_cpm_rnaseq <- voom(rnaseq)
common_genes <- intersect(rownames(collapsed_microarray), rownames(rnaseq))

common_rna <- log2_cpm_rnaseq$E[common_genes,]
common_micro <- collapsed_microarray[common_genes,]

genes_variance <- apply(common_micro, 1, var, na.rm = TRUE)
top_genes_corrected <- names(sort(genes_variance, decreasing = TRUE)[1:1500])
top_corrected <- common_rna[top_genes_corrected, ]
top_array <- common_micro[top_genes_corrected, ]

rnaseq_scaled <- t(scale(t(top_corrected)))
array_scaled <- t(scale(t(top_array)))
array_scaled %>% head()


# Random Forest
model <- randomForest(t(array_scaled), metadata$clusters, ntree = 500)

# Rna data, Random Forest
predictions <- predict(model, t(rnaseq_scaled))

pred_prob <- predict(model, t(rnaseq_scaled), type = "prob")
confidence <- apply(pred_prob, 1, max)
results <- data.frame(
  sample = colnames(rnaseq_scaled),
  dataset = "rna",
  technology = "rna-seq",
  random_forest_cluster = predictions,
  random_forest_confidence = confidence
)
rownames(results) <- NULL
summary(confidence)

print(model)

# Wang data, Random forest

collapsed_wang <- wang %>%
  mutate(variance = rowVars(as.matrix(across(where(is.numeric))))) %>%
  drop_na(Gene) %>%
  group_by(Gene) %>%
  slice_max(order_by = variance, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  arrange(desc(variance)) %>%
  column_to_rownames("Gene") %>% 
  dplyr::select(- ID, - Gene_alt, -variance) %>%
  limma::normalizeBetweenArrays(.)

top_wang <-collapsed_wang[top_genes_corrected,] 
wang_scaled <- t(scale(t(top_wang)))
predictions_wang <- predict(model, t(wang_scaled))

pred_prob_wang <- predict(model, t(wang_scaled), type = "prob")
confidence_wang <- apply(pred_prob_wang, 1, max)
results_wang <- data.frame(
  sample = colnames(wang_scaled),
  dataset = "wang",
  technology = "microarray",
  random_forest_cluster = predictions_wang,
  random_forest_confidence = confidence_wang
)
rownames(results_wang) <- NULL
summary(confidence_wang)

# Random Forest results
results_df <- rbind(results, results_wang)



# Xgboost

labels <- as.numeric(metadata$clusters) - 1

dtrain <- xgb.DMatrix(data = t(array_scaled), label = labels)
dtest_rna <- xgb.DMatrix(data = t(rnaseq_scaled))
dtest_wang <- xgb.DMatrix(data = t(wang_scaled))

params <- list(
  max_depth = 4,
  eta = 0.3,
  objective = "multi:softprob",
  num_class = length(levels(metadata$clusters)),  # 3 clusters
  eval_metric = "mlogloss"
)

model_xgb <- xgb.train(
  data = dtrain,
  params = params,
  nrounds = 500,
  early_stopping_rounds = 100,  # Stop if no improvement after 50 rounds
  evals = list(train = dtrain),  # Optional: monitor training
  verbose = 1  # Shows progress
)
pred_prob_rna <- predict(model_xgb, dtest_rna, type = "prob")
confidence_rna <- apply(pred_prob_rna, 1, max)

pred_prob_wang <- predict(model_xgb, dtest_wang, type = "prob")
confidence_wang <- apply(pred_prob_wang, 1, max)

cluster_names <- levels(metadata$clusters)

xgb_results_rna <- data.frame(
  sample = colnames(rnaseq_scaled),
  xgboost_cluster = cluster_names[apply(pred_prob_rna, 1, which.max)],
  xgboost_confidence = apply(pred_prob_rna, 1, max)
)

xgb_results_wang <- data.frame(
  sample = colnames(wang_scaled),
  xgboost_cluster = cluster_names[apply(pred_prob_wang, 1, which.max)],
  xgboost_confidence = apply(pred_prob_wang, 1, max)
)

xgb_df <- rbind(xgb_results_rna, xgb_results_wang)

results_df <- results_df %>%
  left_join(., xgb_df, by = "sample")
