library(tidyverse)
library(limma)
library(matrixStats)
library(randomForest)
library(xgboost)
library(pls)
library(glmnet)

# Loading data generated by microarray.R
metadata <- read.csv("results/metadata_clusters.csv", row.names = 1)
metadata$clusters <- factor(metadata$clusters)
# Loading data generated by get_microarray_dataset.R
microarray <- read_csv("data/microarray/microarray_dataset.csv")
microarray[,4:70] <- log2(microarray[,4:70] +1)

wang <- read_csv("data/microarray/wang.csv")
wang[,4:12] <- log2(wang[,4:12] + 1)

amani <- read_csv("data/microarray/amani.csv")
amani[,4:113] <- log2(amani[,4:113] + 1)

# Combining to batch correct
expr_microarray <- microarray %>%
  column_to_rownames("ID") %>%
  dplyr::select(-Gene, -Gene_alt) %>%
  as.matrix()

expr_wang <- wang %>%
  column_to_rownames("ID") %>%
  dplyr::select(-Gene, -Gene_alt) %>%
  as.matrix()

expr_amani <- amani %>%
  column_to_rownames("ID") %>%
  dplyr::select(-Gene, -Gene_alt) %>%
  as.matrix()

combined_expr <- cbind(expr_microarray, expr_wang, expr_amani)

batch <- c(
  rep("original", ncol(expr_microarray)),
  rep("wang", ncol(expr_wang)),
  rep("amani", ncol(expr_amani))
)

combined_corrected <- limma::removeBatchEffect(combined_expr, batch = batch)

# data max "iloc" 
micro_iloc <- ncol(expr_microarray)
wang_iloc <- ncol(expr_microarray) + ncol(expr_wang)
amani_iloc <- ncol(expr_microarray) + ncol(expr_wang) + ncol(expr_amani)

# Batch corrected datasets
microarray_corrected <- combined_corrected [, 1:micro_iloc]
wang_corrected <- combined_corrected[, (micro_iloc + 1):wang_iloc]
amani_corrected <- combined_corrected[, (wang_iloc + 1):amani_iloc]

# Globally Scaled batch corrected datasets not used 
# combined_scaled <- t(scale(t(combined_corrected)))

# microarray_scaled <- combined_scaled[, 1:micro_iloc]
# wang_scaled <- combined_scaled[, (micro_iloc + 1):wang_iloc]
# amani_scaled <- combined_scaled[, (wang_iloc + 1):amani_iloc]

# Collapsing multiple probes linked to the same gene
# to the one with highest variance
colapse_probes <- function(target, gene_df){
  gene_corrected <- cbind(gene_df["Gene"], target)
  collapsed_target <- gene_corrected %>%
    mutate(variance = rowVars(as.matrix(across(where(is.numeric))))) %>%
    drop_na(Gene) %>%
    group_by(Gene) %>%
    slice_max(order_by = variance, n = 1, with_ties = FALSE) %>%
    ungroup() %>%
    arrange(desc(variance)) %>%
    column_to_rownames("Gene") %>%
    dplyr::select(-variance)

  collapsed_target
}

collapsed_microarray <- colapse_probes(microarray_corrected, microarray)
collapsed_wang <- colapse_probes(wang_corrected, microarray)
collapsed_amani <- colapse_probes(amani_corrected, microarray)

# Selection the top 1500 most variable genes from the original dataset
top_microarray <- collapsed_microarray[1:1500,]
top_genes <- rownames(top_microarray)

top_wang <- collapsed_wang[top_genes,]
top_amani <- collapsed_amani[top_genes,]


# Random Forest
model <- randomForest(t(top_microarray), metadata$clusters, ntree = 500)
saveRDS(model, file = "models/trained/random_forest.rds")

# Wang data, Random forest
predictions_wang <- predict(model, t(top_wang))
pred_prob_wang <- predict(model, t(top_wang), type = "prob")
confidence_wang <- apply(pred_prob_wang, 1, max)
results_wang <- data.frame(
  sample = colnames(wang_corrected),
  dataset = "wang",
  technology = "microarray",
  random_forest_cluster = predictions_wang,
  random_forest_confidence = confidence_wang
)
rownames(results_wang) <- NULL
summary(confidence_wang)

##
predictions_amani <- predict(model, t(top_amani))
pred_prob_amani <- predict(model, t(top_amani), type = "prob")
confidence_amani <- apply(pred_prob_amani, 1, max)
results_amani <- data.frame(
  sample = colnames(amani_corrected),
  dataset = "amani",
  technology = "microarray",
  random_forest_cluster = predictions_amani,
  random_forest_confidence = confidence_amani
)
rownames(results_amani) <- NULL
summary(confidence_amani)
##
random_forest <- rbind(results_wang, results_amani)

# XGBoost
labels <- as.numeric(metadata$clusters) - 1

dtrain <- xgb.DMatrix(data = t(top_microarray), label = labels)

dtest_wang <- xgb.DMatrix(data = t(top_wang))

params <- list(
  max_depth = 4,
  eta = 0.3,
  objective = "multi:softprob",
  num_class = length(levels(metadata$clusters)),  # 3 clusters
  eval_metric = "mlogloss"
)

model_xgb <- xgb.train(
  data = dtrain,
  params = params,
  nrounds = 500,
  early_stopping_rounds = 100,
  evals = list(train = dtrain),
  verbose = 1
)
saveRDS(model_xgb, file = "models/trained/xgboost.rds")
cluster_names <- levels(metadata$clusters)

pred_prob_wang <- predict(model_xgb, dtest_wang, type = "prob")
confidence_wang <- apply(pred_prob_wang, 1, max)

##
dtest_amani <- xgb.DMatrix(data = t(top_amani))
pred_prob_amani <- predict(model_xgb, dtest_amani, type = "prob")
confidence_amani <- apply(pred_prob_amani, 1, max)
xgb_results_amani <- data.frame(
  sample = colnames(amani_corrected),
  xgboost_cluster = cluster_names[apply(pred_prob_amani, 1, which.max)],
  xgboost_confidence = apply(pred_prob_amani, 1, max)
)
##


xgb_results_wang <- data.frame(
  sample = colnames(wang_corrected),
  xgboost_cluster = cluster_names[apply(pred_prob_wang, 1, which.max)],
  xgboost_confidence = apply(pred_prob_wang, 1, max)
)

xgboost <- rbind(xgb_results_wang, xgb_results_amani)

results_df <- random_forest %>%
  left_join(., xgboost, by = "sample")


# PLS-DA (Partial Least-Squares Discriminant Analysis)
y_train <- metadata$clusters
y_train_dummy <- model.matrix(~ y_train - 1)
x_train <- t(top_microarray)
x_test_wang <- t(top_wang)
x_test_amani <- t(top_amani)

pls_model <- plsr(y_train_dummy ~ x_train, ncomp = 3)
saveRDS(pls_model, file = "models/trained/plsda.rds")

pred_scores_wang <- predict(pls_model, newdata = x_test_wang, ncomp = 3)
test_proj_wang <- predict(pls_model, newdata = x_test_wang, type = "scores")

pred_class_wang <- apply(pred_scores_wang, 1, which.max)
pred_classes_wang   <- levels(y_train)[pred_class_wang]

get_probs <- function(x) { exp(x) / sum(exp(x)) }
pls_probs_wang <- t(apply(pred_scores_wang, 1, get_probs))

pls_results_wang <- data.frame(
  sample = rownames(x_test_wang),
  pls_cluster = pred_classes_wang,
  pls_confidence = apply(pls_probs_wang, 1, max)
)

test_scores_wang <- data.frame(
  Comp1 = test_proj_wang[, 1],
  Comp2 = test_proj_wang[, 2],
  Group = pred_classes_wang,
  Set   = "Wang"
)
##
pred_scores_amani <- predict(pls_model, newdata = x_test_amani, ncomp = 3)
test_proj_amani <- predict(pls_model, newdata = x_test_amani, type = "scores")

pred_class_amani <- apply(pred_scores_amani, 1, which.max)
pred_classes_amani   <- levels(y_train)[pred_class_amani]

get_probs <- function(x) { exp(x) / sum(exp(x)) }
pls_probs_amani <- t(apply(pred_scores_amani, 1, get_probs))

pls_results_amani <- data.frame(
  sample = rownames(x_test_amani),
  pls_cluster = pred_classes_amani,
  pls_confidence = apply(pls_probs_amani, 1, max)
)

test_scores_amani <- data.frame(
  Comp1 = test_proj_amani[, 1],
  Comp2 = test_proj_amani[, 2],
  Group = pred_classes_amani,
  Set   = "Amani"
)
##
train_scores <- data.frame(
  Comp1 = scores(pls_model)[, 1],
  Comp2 = scores(pls_model)[, 2],
  Group = y_train,
  Set   = "Pascal"
)

all_scores <- rbind(train_scores, test_scores_wang, test_scores_amani)

plsda <- rbind(pls_results_wang, pls_results_amani)

results_df <- results_df %>%
  left_join(., plsda, by = "sample")

# Plot - PLS-DA
ggplot(all_scores, aes(x = Comp1, y = Comp2, color = Group, shape = Set)) +
  geom_point(size = 3, alpha = 0.7) +                 
  stat_ellipse(data = train_scores, level = 0.95) +   
  theme_minimal() +
  labs(title = "PLS-DA: Training vs Test Data",
       subtitle = "Ellipses are 95% Confidence Intervals.",
       x = "Latent Component 1", y = "Latent Component 2")

# Penalized Logistic Regression - glmnet
y_train <- metadata$clusters
x_train <- t(top_microarray)

cv_fit <- cv.glmnet(
  x = x_train,
  y = y_train,
  family = "multinomial",
  alpha = 1,  # Lasso for feature selection
  nfolds = 5  # Use 5-fold CV due to small sample size
)
saveRDS(cv_fit, file = "models/trained/glmnet.rds")
coefs <- coef(cv_fit, s = "lambda.min")

x_test_wang <- t(top_wang)
pred_probs_glmnet <- predict(cv_fit, x_test_wang, type = "response", s = "lambda.min")

glmnet_results_wang <- data.frame(
  sample = colnames(wang_corrected),
  glmnet_cluster = colnames(pred_probs_glmnet)[apply(pred_probs_glmnet, 1, which.max)],
  glmnet_confidence = apply(pred_probs_glmnet, 1, max)
)

##
x_test_amani <- t(top_amani)
pred_probs_glmnet <- predict(cv_fit, x_test_amani, type = "response", s = "lambda.min")

glmnet_results_amani <- data.frame(
  sample = colnames(amani_corrected),
  glmnet_cluster = colnames(pred_probs_glmnet)[apply(pred_probs_glmnet, 1, which.max)],
  glmnet_confidence = apply(pred_probs_glmnet, 1, max)
)
##

glmnet <- rbind(glmnet_results_wang, glmnet_results_amani)

results_df <- results_df %>%
  left_join(., glmnet, by = "sample")
